import 'package:moment_dart/moment_dart.dart';
import 'package:test/test.dart';

void main() {
  // See MomentLocalization.__relativeThresholds for more info on defined values.
  final now = Moment.now();
  final fewMomentsAhead = now + const Duration(seconds: 44);
  final fewMomentsAgo = now - const Duration(seconds: 44);
  final aMinuteAhead = now + const Duration(seconds: 46);
  final aMinuteAgo = now - const Duration(seconds: 46);
  final fiveMinutesAhead = now + const Duration(minutes: 5);
  final fiveMinutesAgo = now - const Duration(minutes: 5);
  final anHourAhead = now + const Duration(minutes: 46);
  final anHourAgo = now - const Duration(minutes: 46);
  final sixHoursAhead = now + const Duration(hours: 6);
  final sixHoursAgo = now - const Duration(hours: 6);
  final aDayAhead = now + const Duration(hours: 35);
  final aDayAgo = now - const Duration(hours: 35);
  final twoDaysAhead = now + const Duration(days: 2);
  final twoDaysAgo = now - const Duration(days: 2);
  final aMonthAhead = now + const Duration(days: 44);
  final aMonthAgo = now - const Duration(days: 44);
  final fourMonthsAhead = now + const Duration(days: 120);
  final fourMonthsAgo = now - const Duration(days: 120);
  final aYearAhead = now + const Duration(days: 547);
  final aYearAgo = now - const Duration(days: 547);
  final threeYearsAhead = now + const Duration(days: 365 * 3 + 1);
  final threeYearsAgo = now - const Duration(days: 365 * 3 + 1);

  void _setLocalization(MomentLocalization localization) {
    fewMomentsAhead.setLocalization(localization);
    fewMomentsAgo.setLocalization(localization);
    aMinuteAhead.setLocalization(localization);
    aMinuteAgo.setLocalization(localization);
    fiveMinutesAhead.setLocalization(localization);
    fiveMinutesAgo.setLocalization(localization);
    anHourAhead.setLocalization(localization);
    anHourAgo.setLocalization(localization);
    sixHoursAhead.setLocalization(localization);
    sixHoursAgo.setLocalization(localization);
    aDayAhead.setLocalization(localization);
    aDayAgo.setLocalization(localization);
    twoDaysAhead.setLocalization(localization);
    twoDaysAgo.setLocalization(localization);
    aMonthAhead.setLocalization(localization);
    aMonthAgo.setLocalization(localization);
    fourMonthsAhead.setLocalization(localization);
    fourMonthsAgo.setLocalization(localization);
    aYearAhead.setLocalization(localization);
    aYearAgo.setLocalization(localization);
    threeYearsAhead.setLocalization(localization);
    threeYearsAgo.setLocalization(localization);
  }

  test("de_DE localization relative time test", () {
    _setLocalization(MomentLocalizations.deDE());

    expect(fewMomentsAhead.from(now), "in wenigen Sekunden");
    expect(fewMomentsAgo.from(now), "vor wenigen Sekunden");
    expect(fewMomentsAgo.from(now, true), "wenigen Sekunden");
    expect(aMinuteAhead.from(now), "in einer Minute");
    expect(aMinuteAgo.from(now), "vor einer Minute");
    expect(aMinuteAgo.from(now, true), "einer Minute");
    expect(fiveMinutesAhead.from(now), "in 5 Minuten");
    expect(fiveMinutesAgo.from(now), "vor 5 Minuten");
    expect(fiveMinutesAgo.from(now, true), "5 Minuten");
    expect(anHourAhead.from(now), "in einer Stunde");
    expect(anHourAgo.from(now), "vor einer Stunde");
    expect(anHourAgo.from(now, true), "einer Stunde");
    expect(sixHoursAhead.from(now), "in 6 Stunden");
    expect(sixHoursAgo.from(now), "vor 6 Stunden");
    expect(sixHoursAgo.from(now, true), "6 Stunden");
    expect(aDayAhead.from(now), "in einem Tag");
    expect(aDayAgo.from(now), "vor einem Tag");
    expect(aDayAgo.from(now, true), "einem Tag");
    expect(twoDaysAhead.from(now), "in 2 Tagen");
    expect(twoDaysAgo.from(now), "vor 2 Tagen");
    expect(twoDaysAgo.from(now, true), "2 Tagen");
    expect(aMonthAhead.from(now), "in einem Monat");
    expect(aMonthAgo.from(now), "vor einem Monat");
    expect(aMonthAgo.from(now, true), "einem Monat");
    expect(fourMonthsAhead.from(now), "in 4 Monaten");
    expect(fourMonthsAgo.from(now), "vor 4 Monaten");
    expect(fourMonthsAgo.from(now, true), "4 Monaten");
    expect(aYearAhead.from(now), "in einem Jahr");
    expect(aYearAgo.from(now), "vor einem Jahr");
    expect(aYearAgo.from(now, true), "einem Jahr");
    expect(threeYearsAhead.from(now), "in 3 Jahren");
    expect(threeYearsAgo.from(now), "vor 3 Jahren");
    expect(threeYearsAgo.from(now, true), "3 Jahren");
  });

  test("fr localization relative time test", () {
    _setLocalization(MomentLocalizations.fr());

    expect(fewMomentsAhead.from(now), "dans quelques secondes");
    expect(fewMomentsAgo.from(now), "il y a quelques secondes");
    expect(fewMomentsAgo.from(now, true), "quelques secondes");
    expect(aMinuteAhead.from(now), "dans une minute");
    expect(aMinuteAgo.from(now), "il y a une minute");
    expect(aMinuteAgo.from(now, true), "une minute");
    expect(fiveMinutesAhead.from(now), "dans 5 minutes");
    expect(fiveMinutesAgo.from(now), "il y a 5 minutes");
    expect(fiveMinutesAgo.from(now, true), "5 minutes");
    expect(anHourAhead.from(now), "dans une heure");
    expect(anHourAgo.from(now), "il y a une heure");
    expect(anHourAgo.from(now, true), "une heure");
    expect(sixHoursAhead.from(now), "dans 6 heures");
    expect(sixHoursAgo.from(now), "il y a 6 heures");
    expect(sixHoursAgo.from(now, true), "6 heures");
    expect(aDayAhead.from(now), "dans un jour");
    expect(aDayAgo.from(now), "il y a un jour");
    expect(aDayAgo.from(now, true), "un jour");
    expect(twoDaysAhead.from(now), "dans 2 jours");
    expect(twoDaysAgo.from(now), "il y a 2 jours");
    expect(twoDaysAgo.from(now, true), "2 jours");
    expect(aMonthAhead.from(now), "dans un mois");
    expect(aMonthAgo.from(now), "il y a un mois");
    expect(aMonthAgo.from(now, true), "un mois");
    expect(fourMonthsAhead.from(now), "dans 4 mois");
    expect(fourMonthsAgo.from(now), "il y a 4 mois");
    expect(fourMonthsAgo.from(now, true), "4 mois");
    expect(aYearAhead.from(now), "dans un an");
    expect(aYearAgo.from(now), "il y a un an");
    expect(aYearAgo.from(now, true), "un an");
    expect(threeYearsAhead.from(now), "dans 3 ans");
    expect(threeYearsAgo.from(now), "il y a 3 ans");
    expect(threeYearsAgo.from(now, true), "3 ans");
  });

  test("es localization relative time test", () {
    _setLocalization(MomentLocalizations.es());

    expect(fewMomentsAhead.from(now), "en unos segundos");
    expect(fewMomentsAgo.from(now), "hace unos segundos");
    expect(fewMomentsAgo.from(now, true), "unos segundos");
    expect(aMinuteAhead.from(now), "en un minuto");
    expect(aMinuteAgo.from(now), "hace un minuto");
    expect(aMinuteAgo.from(now, true), "un minuto");
    expect(fiveMinutesAhead.from(now), "en 5 minutos");
    expect(fiveMinutesAgo.from(now), "hace 5 minutos");
    expect(fiveMinutesAgo.from(now, true), "5 minutos");
    expect(anHourAhead.from(now), "en un hora");
    expect(anHourAgo.from(now), "hace un hora");
    expect(anHourAgo.from(now, true), "un hora");
    expect(sixHoursAhead.from(now), "en 6 horas");
    expect(sixHoursAgo.from(now), "hace 6 horas");
    expect(sixHoursAgo.from(now, true), "6 horas");
    expect(aDayAhead.from(now), "en un día");
    expect(aDayAgo.from(now), "hace un día");
    expect(aDayAgo.from(now, true), "un día");
    expect(twoDaysAhead.from(now), "en 2 días");
    expect(twoDaysAgo.from(now), "hace 2 días");
    expect(twoDaysAgo.from(now, true), "2 días");
    expect(aMonthAhead.from(now), "en un mes");
    expect(aMonthAgo.from(now), "hace un mes");
    expect(aMonthAgo.from(now, true), "un mes");
    expect(fourMonthsAhead.from(now), "en 4 meses");
    expect(fourMonthsAgo.from(now), "hace 4 meses");
    expect(fourMonthsAgo.from(now, true), "4 meses");
    expect(aYearAhead.from(now), "en un año");
    expect(aYearAgo.from(now), "hace un año");
    expect(aYearAgo.from(now, true), "un año");
    expect(threeYearsAhead.from(now), "en 3 años");
    expect(threeYearsAgo.from(now), "hace 3 años");
    expect(threeYearsAgo.from(now, true), "3 años");
  });

  test("en_US localization relative time test", () {
    _setLocalization(MomentLocalizations.enUS());

    expect(fewMomentsAhead.from(now), "in a few seconds");
    expect(fewMomentsAgo.from(now), "a few seconds ago");
    expect(fewMomentsAgo.from(now, true), "a few seconds");
    expect(aMinuteAhead.from(now), "in a minute");
    expect(aMinuteAgo.from(now), "a minute ago");
    expect(aMinuteAgo.from(now, true), "a minute");
    expect(fiveMinutesAhead.from(now), "in 5 minutes");
    expect(fiveMinutesAgo.from(now), "5 minutes ago");
    expect(fiveMinutesAgo.from(now, true), "5 minutes");
    expect(anHourAhead.from(now), "in an hour");
    expect(anHourAgo.from(now), "an hour ago");
    expect(anHourAgo.from(now, true), "an hour");
    expect(sixHoursAhead.from(now), "in 6 hours");
    expect(sixHoursAgo.from(now), "6 hours ago");
    expect(sixHoursAgo.from(now, true), "6 hours");
    expect(aDayAhead.from(now), "in a day");
    expect(aDayAgo.from(now), "a day ago");
    expect(aDayAgo.from(now, true), "a day");
    expect(twoDaysAhead.from(now), "in 2 days");
    expect(twoDaysAgo.from(now), "2 days ago");
    expect(twoDaysAgo.from(now, true), "2 days");
    expect(aMonthAhead.from(now), "in a month");
    expect(aMonthAgo.from(now), "a month ago");
    expect(aMonthAgo.from(now, true), "a month");
    expect(fourMonthsAhead.from(now), "in 4 months");
    expect(fourMonthsAgo.from(now), "4 months ago");
    expect(fourMonthsAgo.from(now, true), "4 months");
    expect(aYearAhead.from(now), "in a year");
    expect(aYearAgo.from(now), "a year ago");
    expect(aYearAgo.from(now, true), "a year");
    expect(threeYearsAhead.from(now), "in 3 years");
    expect(threeYearsAgo.from(now), "3 years ago");
    expect(threeYearsAgo.from(now, true), "3 years");
  });

  test("mn localization relative time test", () {
    _setLocalization(MomentLocalizations.mn());

    expect(fewMomentsAhead.from(now), "хэдэн хормын дараа");
    expect(fewMomentsAgo.from(now), "хэдэн хормын өмнө");
    expect(fewMomentsAgo.from(now, true), "хэдэн хором");
    expect(aMinuteAhead.from(now), "1 минутын дараа");
    expect(aMinuteAgo.from(now), "1 минутын өмнө");
    expect(aMinuteAgo.from(now, true), "1 минут");
    expect(fiveMinutesAhead.from(now), "5 минутын дараа");
    expect(fiveMinutesAgo.from(now), "5 минутын өмнө");
    expect(fiveMinutesAgo.from(now, true), "5 минут");
    expect(anHourAhead.from(now), "1 цагийн дараа");
    expect(anHourAgo.from(now), "1 цагийн өмнө");
    expect(anHourAgo.from(now, true), "1 цаг");
    expect(sixHoursAhead.from(now), "6 цагийн дараа");
    expect(sixHoursAgo.from(now), "6 цагийн өмнө");
    expect(sixHoursAgo.from(now, true), "6 цаг");
    expect(aDayAhead.from(now), "1 өдрийн дараа");
    expect(aDayAgo.from(now), "1 өдрийн өмнө");
    expect(aDayAgo.from(now, true), "1 өдөр");
    expect(twoDaysAhead.from(now), "2 өдрийн дараа");
    expect(twoDaysAgo.from(now), "2 өдрийн өмнө");
    expect(twoDaysAgo.from(now, true), "2 өдөр");
    expect(aMonthAhead.from(now), "1 сарын дараа");
    expect(aMonthAgo.from(now), "1 сарын өмнө");
    expect(aMonthAgo.from(now, true), "1 сар");
    expect(fourMonthsAhead.from(now), "4 сарын дараа");
    expect(fourMonthsAgo.from(now), "4 сарын өмнө");
    expect(fourMonthsAgo.from(now, true), "4 сар");
    expect(aYearAhead.from(now), "1 жилийн дараа");
    expect(aYearAgo.from(now), "1 жилийн өмнө");
    expect(aYearAgo.from(now, true), "1 жил");
    expect(threeYearsAhead.from(now), "3 жилийн дараа");
    expect(threeYearsAgo.from(now), "3 жилийн өмнө");
    expect(threeYearsAgo.from(now, true), "3 жил");
  });

  test("mn (Traditional) localization relative time test", () {
    _setLocalization(MomentLocalizations.mnTM());

    expect(fewMomentsAhead.from(now), "ᠬᠡᠳᠦᠨ ᠬᠣᠷᠤᠮ ᠤᠨ ᠳᠠᠷᠠᠭ᠎ᠠ");
    expect(fewMomentsAgo.from(now), "ᠬᠡᠳᠦᠨ ᠬᠣᠷᠤᠮ ᠤᠨ ᠡᠮᠦᠨ᠎ᠡ");
    expect(fewMomentsAgo.from(now, true), "ᠬᠡᠳᠦᠨ ᠬᠣᠷᠤᠮ");
    expect(aMinuteAhead.from(now), "1 ᠮᠢᠨᠦ᠋ᠲ᠋ ᠦᠨ ᠳᠠᠷᠠᠭ᠎ᠠ");
    expect(aMinuteAgo.from(now), "1 ᠮᠢᠨᠦ᠋ᠲ᠋ ᠦᠨ ᠡᠮᠦᠨ᠎ᠡ");
    expect(aMinuteAgo.from(now, true), "1 ᠮᠢᠨᠦ᠋ᠲ᠋");
    expect(fiveMinutesAhead.from(now), "5 ᠮᠢᠨᠦ᠋ᠲ᠋ ᠦᠨ ᠳᠠᠷᠠᠭ᠎ᠠ");
    expect(fiveMinutesAgo.from(now), "5 ᠮᠢᠨᠦ᠋ᠲ᠋ ᠦᠨ ᠡᠮᠦᠨ᠎ᠡ");
    expect(fiveMinutesAgo.from(now, true), "5 ᠮᠢᠨᠦ᠋ᠲ᠋");
    expect(anHourAhead.from(now), "1 ᠴᠠᠭ ᠤᠨ ᠳᠠᠷᠠᠭ᠎ᠠ");
    expect(anHourAgo.from(now), "1 ᠴᠠᠭ ᠤᠨ ᠡᠮᠦᠨ᠎ᠡ");
    expect(anHourAgo.from(now, true), "1 ᠴᠠᠭ");
    expect(sixHoursAhead.from(now), "6 ᠴᠠᠭ ᠤᠨ ᠳᠠᠷᠠᠭ᠎ᠠ");
    expect(sixHoursAgo.from(now), "6 ᠴᠠᠭ ᠤᠨ ᠡᠮᠦᠨ᠎ᠡ");
    expect(sixHoursAgo.from(now, true), "6 ᠴᠠᠭ");
    expect(aDayAhead.from(now), "1 ᠡᠳᠦᠷ ᠦᠨ ᠳᠠᠷᠠᠭ᠎ᠠ");
    expect(aDayAgo.from(now), "1 ᠡᠳᠦᠷ ᠦᠨ ᠡᠮᠦᠨ᠎ᠡ");
    expect(aDayAgo.from(now, true), "1 ᠡᠳᠦᠷ");
    expect(twoDaysAhead.from(now), "2 ᠡᠳᠦᠷ ᠦᠨ ᠳᠠᠷᠠᠭ᠎ᠠ");
    expect(twoDaysAgo.from(now), "2 ᠡᠳᠦᠷ ᠦᠨ ᠡᠮᠦᠨ᠎ᠡ");
    expect(twoDaysAgo.from(now, true), "2 ᠡᠳᠦᠷ");
    expect(aMonthAhead.from(now), "1 ᠰᠠᠷ᠎ᠠ ᠶᠢᠨ ᠳᠠᠷᠠᠭ᠎ᠠ");
    expect(aMonthAgo.from(now), "1 ᠰᠠᠷ᠎ᠠ ᠶᠢᠨ ᠡᠮᠦᠨ᠎ᠡ");
    expect(aMonthAgo.from(now, true), "1 ᠰᠠᠷ᠎ᠠ");
    expect(fourMonthsAhead.from(now), "4 ᠰᠠᠷ᠎ᠠ ᠶᠢᠨ ᠳᠠᠷᠠᠭ᠎ᠠ");
    expect(fourMonthsAgo.from(now), "4 ᠰᠠᠷ᠎ᠠ ᠶᠢᠨ ᠡᠮᠦᠨ᠎ᠡ");
    expect(fourMonthsAgo.from(now, true), "4 ᠰᠠᠷ᠎ᠠ");
    expect(aYearAhead.from(now), "1 ᠵᠢᠯ ᠤᠨ ᠳᠠᠷᠠᠭ᠎ᠠ");
    expect(aYearAgo.from(now), "1 ᠵᠢᠯ ᠤᠨ ᠡᠮᠦᠨ᠎ᠡ");
    expect(aYearAgo.from(now, true), "1 ᠵᠢᠯ");
    expect(threeYearsAhead.from(now), "3 ᠵᠢᠯ ᠤᠨ ᠳᠠᠷᠠᠭ᠎ᠠ");
    expect(threeYearsAgo.from(now), "3 ᠵᠢᠯ ᠤᠨ ᠡᠮᠦᠨ᠎ᠡ");
    expect(threeYearsAgo.from(now, true), "3 ᠵᠢᠯ");
  });

  test("mn (Traditional with numbers) localization relative time test", () {
    _setLocalization(MomentLocalizations.mnTMtn());

    expect(fewMomentsAhead.from(now), "ᠬᠡᠳᠦᠨ ᠬᠣᠷᠤᠮ ᠤᠨ ᠳᠠᠷᠠᠭ᠎ᠠ");
    expect(fewMomentsAgo.from(now), "ᠬᠡᠳᠦᠨ ᠬᠣᠷᠤᠮ ᠤᠨ ᠡᠮᠦᠨ᠎ᠡ");
    expect(fewMomentsAgo.from(now, true), "ᠬᠡᠳᠦᠨ ᠬᠣᠷᠤᠮ");
    expect(aMinuteAhead.from(now), "᠑ ᠮᠢᠨᠦ᠋ᠲ᠋ ᠦᠨ ᠳᠠᠷᠠᠭ᠎ᠠ");
    expect(aMinuteAgo.from(now), "᠑ ᠮᠢᠨᠦ᠋ᠲ᠋ ᠦᠨ ᠡᠮᠦᠨ᠎ᠡ");
    expect(aMinuteAgo.from(now, true), "᠑ ᠮᠢᠨᠦ᠋ᠲ᠋");
    expect(fiveMinutesAhead.from(now), "᠕ ᠮᠢᠨᠦ᠋ᠲ᠋ ᠦᠨ ᠳᠠᠷᠠᠭ᠎ᠠ");
    expect(fiveMinutesAgo.from(now), "᠕ ᠮᠢᠨᠦ᠋ᠲ᠋ ᠦᠨ ᠡᠮᠦᠨ᠎ᠡ");
    expect(fiveMinutesAgo.from(now, true), "᠕ ᠮᠢᠨᠦ᠋ᠲ᠋");
    expect(anHourAhead.from(now), "᠑ ᠴᠠᠭ ᠤᠨ ᠳᠠᠷᠠᠭ᠎ᠠ");
    expect(anHourAgo.from(now), "᠑ ᠴᠠᠭ ᠤᠨ ᠡᠮᠦᠨ᠎ᠡ");
    expect(anHourAgo.from(now, true), "᠑ ᠴᠠᠭ");
    expect(sixHoursAhead.from(now), "᠖ ᠴᠠᠭ ᠤᠨ ᠳᠠᠷᠠᠭ᠎ᠠ");
    expect(sixHoursAgo.from(now), "᠖ ᠴᠠᠭ ᠤᠨ ᠡᠮᠦᠨ᠎ᠡ");
    expect(sixHoursAgo.from(now, true), "᠖ ᠴᠠᠭ");
    expect(aDayAhead.from(now), "᠑ ᠡᠳᠦᠷ ᠦᠨ ᠳᠠᠷᠠᠭ᠎ᠠ");
    expect(aDayAgo.from(now), "᠑ ᠡᠳᠦᠷ ᠦᠨ ᠡᠮᠦᠨ᠎ᠡ");
    expect(aDayAgo.from(now, true), "᠑ ᠡᠳᠦᠷ");
    expect(twoDaysAhead.from(now), "᠒ ᠡᠳᠦᠷ ᠦᠨ ᠳᠠᠷᠠᠭ᠎ᠠ");
    expect(twoDaysAgo.from(now), "᠒ ᠡᠳᠦᠷ ᠦᠨ ᠡᠮᠦᠨ᠎ᠡ");
    expect(twoDaysAgo.from(now, true), "᠒ ᠡᠳᠦᠷ");
    expect(aMonthAhead.from(now), "᠑ ᠰᠠᠷ᠎ᠠ ᠶᠢᠨ ᠳᠠᠷᠠᠭ᠎ᠠ");
    expect(aMonthAgo.from(now), "᠑ ᠰᠠᠷ᠎ᠠ ᠶᠢᠨ ᠡᠮᠦᠨ᠎ᠡ");
    expect(aMonthAgo.from(now, true), "᠑ ᠰᠠᠷ᠎ᠠ");
    expect(fourMonthsAhead.from(now), "᠔ ᠰᠠᠷ᠎ᠠ ᠶᠢᠨ ᠳᠠᠷᠠᠭ᠎ᠠ");
    expect(fourMonthsAgo.from(now), "᠔ ᠰᠠᠷ᠎ᠠ ᠶᠢᠨ ᠡᠮᠦᠨ᠎ᠡ");
    expect(fourMonthsAgo.from(now, true), "᠔ ᠰᠠᠷ᠎ᠠ");
    expect(aYearAhead.from(now), "᠑ ᠵᠢᠯ ᠤᠨ ᠳᠠᠷᠠᠭ᠎ᠠ");
    expect(aYearAgo.from(now), "᠑ ᠵᠢᠯ ᠤᠨ ᠡᠮᠦᠨ᠎ᠡ");
    expect(aYearAgo.from(now, true), "᠑ ᠵᠢᠯ");
    expect(threeYearsAhead.from(now), "᠓ ᠵᠢᠯ ᠤᠨ ᠳᠠᠷᠠᠭ᠎ᠠ");
    expect(threeYearsAgo.from(now), "᠓ ᠵᠢᠯ ᠤᠨ ᠡᠮᠦᠨ᠎ᠡ");
    expect(threeYearsAgo.from(now, true), "᠓ ᠵᠢᠯ");
  });

  test("ko localization relative time test", () {
    _setLocalization(MomentLocalizations.ko());

    expect(fewMomentsAhead.from(now), "몇 초 후");
    expect(fewMomentsAgo.from(now), "몇 초 전");
    expect(fewMomentsAgo.from(now, true), "몇 초");
    expect(aMinuteAhead.from(now), "1분 후");
    expect(aMinuteAgo.from(now), "1분 전");
    expect(aMinuteAgo.from(now, true), "1분");
    expect(fiveMinutesAhead.from(now), "5분 후");
    expect(fiveMinutesAgo.from(now), "5분 전");
    expect(fiveMinutesAgo.from(now, true), "5분");
    expect(anHourAhead.from(now), "1시간 후");
    expect(anHourAgo.from(now), "1시간 전");
    expect(anHourAgo.from(now, true), "1시간");
    expect(sixHoursAhead.from(now), "6시간 후");
    expect(sixHoursAgo.from(now), "6시간 전");
    expect(sixHoursAgo.from(now, true), "6시간");
    expect(aDayAhead.from(now), "1일 후");
    expect(aDayAgo.from(now), "1일 전");
    expect(aDayAgo.from(now, true), "1일");
    expect(twoDaysAhead.from(now), "2일 후");
    expect(twoDaysAgo.from(now), "2일 전");
    expect(twoDaysAgo.from(now, true), "2일");
    expect(aMonthAhead.from(now), "1개월 후");
    expect(aMonthAgo.from(now), "1개월 전");
    expect(aMonthAgo.from(now, true), "1개월");
    expect(fourMonthsAhead.from(now), "4개월 후");
    expect(fourMonthsAgo.from(now), "4개월 전");
    expect(fourMonthsAgo.from(now, true), "4개월");
    expect(aYearAhead.from(now), "1년 후");
    expect(aYearAgo.from(now), "1년 전");
    expect(aYearAgo.from(now, true), "1년");
    expect(threeYearsAhead.from(now), "3년 후");
    expect(threeYearsAgo.from(now), "3년 전");
    expect(threeYearsAgo.from(now, true), "3년");
    expect(threeYearsAgo.from(now, true), "3년");
  });
}
